version: '3'

services:
  db:
    image: postgres:10.4
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgreSQL
    restart: always
    environment:
      POSTGRES_ROOT_PASSWORD: postgres
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - backend

  wheather-backend:
    depends_on:
      - db
    image: aliniribeiroo/wheather:latest
    ports:
      - "8080:8080"
    restart: always
    environment:
      DB_HOST: jdbc:postgresql://db:5432/wheather
      DB_USER: postgres
      DB_PASSWORD: postgres
    networks:
      - backend
  web:
    image: aliniribeiroo/wheather-frontend:latest
    ports:
      - "4200:4200"
    networks:
      - backend
volumes:
  db_data:

### Networks Setup ############################################
networks:
  backend:
    driver: "bridge"